site_name: ${{ values.name }}
site_description: ${{ values.description | default("A new service") }}

repo_url: ${{ values.repoUrl | default("https://github.com/josefernandezceiba/bs-test-001") }}
edit_uri: edit/main/docs

plugins: 
  - techdocs-core

nav:
  - Home: index.md